version: "3.8"

services:
  app:
    image: php:8.2-fpm
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db_exam
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: mengleang-db
      MYSQL_ROOT_PASSWORD: Hello@123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
