---
- name: Laravel Web App Deployment and Testing
  hosts: localhost
  gather_facts: false

  vars:
    web_pod: laravel-app-66f4668b9b-hkqzn     # Change to your web pod name
    web_container: web
    mysql_pod: laravel-app-66f4668b9b-hkqzn   # Change to your MySQL pod name if different
    mysql_container: mysql
    backup_file: /tmp/mysql_backup_{{ ansible_date_time.iso8601 }}.sql
    prod_db_user: root
    prod_db_password: "your_mysql_root_password"
    prod_db_name: your_production_database_name

  tasks:

    - name: Check for local git changes on web pod
      shell: |
        kubectl exec {{ web_pod }} -c {{ web_container }} -- bash -c "cd /var/www/html && git diff --quiet"
      register: git_diff
      failed_when: git_diff.rc != 0
      ignore_errors: false

    - name: Pull latest code on web pod
      shell: |
        kubectl exec {{ web_pod }} -c {{ web_container }} -- bash -c "cd /var/www/html && git pull"
      when: git_diff.rc == 0

    - name: Run composer install on web pod
      shell: |
        kubectl exec {{ web_pod }} -c {{ web_container }} -- bash -c "cd /var/www/html && composer install --no-interaction --prefer-dist --optimize-autoloader"

    - name: Run npm install and build on web pod
      shell: |
        kubectl exec {{ web_pod }} -c {{ web_container }} -- bash -c "cd /var/www/html && npm install && npm run build"

    - name: Run PHPUnit tests using SQLite on web pod
      shell: |
        kubectl exec {{ web_pod }} -c {{ web_container }} -- bash -c "cd /var/www/html && ./vendor/bin/phpunit"
      environment:
        DB_CONNECTION: sqlite
        DB_DATABASE: /var/www/html/database/testing.sqlite

    - name: Backup MySQL production database
      shell: |
        kubectl exec {{ mysql_pod }} -c {{ mysql_container }} -- bash -c "mysqldump -u{{ prod_db_user }} -p'{{ prod_db_password }}' {{ prod_db_name }} > {{ backup_file }}"

    - name: Copy MySQL backup file from pod to local
      shell: |
        kubectl cp {{ mysql_pod }}:{{ backup_file }} ./mysql_backup.sql -c {{ mysql_container }}
